site_name: XiangShan官方文档
theme:
    name: readthedocs
    language: zh
    locale: zh_CN
nav:
    - 简介:
        - 写前必读: index.md
        - 香山项目总体介绍: intro.md
        - 香山总体架构: arch.md
    - 处理器核介绍:
        - 前端:
            - 总体架构: frontend/frontend.md
            - IFU: frontend/ifu.md
            - ICache: frontend/icache.md
            - 分支预测: frontend/bp.md
            - 取指目标队列: frontend/ftq.md
            - Decode Stage: frontend/decode.md
        - 后端:
            - Rename Stage: rename.md
            - Dispatch Stage: dispatch.md
            - ROB: rob.md
        - 访存子系统:
            - LSQ: ldq.md
        - L2/L3 Cache:
            - 总体架构: huancun/overview.md
            - 目录设计: huancun/directory.md
            - 数据存储: huancun/data.md
            - MSHR: huancun/mshr.md
            - 通道控制: huancun/channels.md
            - L2预取: huancun/prefetch.md
            - Cache 别名问题: huancun/cache_alias.md
            - Miscs:
                - RequestBuffer: huancun/req_buffer.md
                - RefillBuffer: huancun/refill_buffer.md
                - MSHRAlloc: huancun/alloc.md
                - ProbeHelper: huancun/probe_helper.md
    - 敏捷验证框架:
        - DiffTest: difftest.md
        - LightSSS: lightsss.md
